import type { ReactNode } from "react";
import type { AtlasIR } from "../../core/ir";
import { serializeAtlasIR, validateAtlasIR } from "../../core/ir";
import type { AtlasSolveResult, AtlasSolutionState } from "../../core/solution";
import type { AtlasRuntimeDiagnostic } from "../../core/runtimeDiagnostics";
import { ATLAS_VIEW_REGISTRY } from "./viewRegistry";

export type AtlasWorkbenchView = "object" | "ir" | "code" | "solution" | "diagnostics";

export type AtlasGeneratedCodeState =
  | { status: "empty" }
  | { status: "loading"; previous?: string | null; stale?: boolean }
  | { status: "success"; code: string; stale: boolean }
  | { status: "error"; message: string; previous?: string | null; stale?: boolean };

export type AtlasViewDiagnostic = {
  id: string;
  level: "info" | "warning" | "error";
  message: string;
  sourceId?: string | null;
};

export function AtlasViewTabs({
  activeView,
  onChange
}: {
  activeView: AtlasWorkbenchView;
  onChange: (view: AtlasWorkbenchView) => void;
}) {
  return (
    <nav className="atlas-view-tabs" aria-label="Atlas synchronized model views">
      {ATLAS_VIEW_REGISTRY.map((tab) => (
        <button
          key={tab.id}
          type="button"
          className={activeView === tab.id ? "active" : undefined}
          aria-pressed={activeView === tab.id}
          onClick={() => onChange(tab.id)}
        >
          {tab.title}
        </button>
      ))}
    </nav>
  );
}

export function AtlasIRView({
  ir,
  onExport,
  onImport
}: {
  ir: AtlasIR;
  onExport: () => void;
  onImport: () => void;
}) {
  const serialized = serializeAtlasIR(ir);
  return (
    <section className="atlas-view-panel atlas-ir-view" aria-label="Atlas IR View">
      <ViewHeader
        eyebrow="Atlas IR"
        title="Current model JSON"
        description="Read-only view of the same model used by the graphical workbench."
      >
        <button type="button" onClick={onExport}>Export IR</button>
        <button type="button" onClick={onImport}>Import IR</button>
      </ViewHeader>
      <pre className="atlas-code-block" aria-label="Current Atlas IR JSON">{serialized}</pre>
    </section>
  );
}

export function AtlasCodeView({
  codeState,
  solution,
  backendStatus,
  onGenerateCode
}: {
  codeState: AtlasGeneratedCodeState;
  solution: AtlasSolutionState;
  backendStatus: "unknown" | "connected" | "unavailable";
  onGenerateCode: () => void;
}) {
  const solutionCode = solution.status === "success" ? solution.result.code : null;
  const visibleCode =
    codeState.status === "success"
      ? codeState.code
      : codeState.status === "loading" || codeState.status === "error"
        ? codeState.previous
        : solutionCode;

  return (
    <section className="atlas-view-panel atlas-code-view" aria-label="CVXPY Code View">
      <ViewHeader
        eyebrow="CVXPY"
        title="Generated Python code"
        description="Generated by the backend from the current Atlas IR."
      >
        <button type="button" onClick={onGenerateCode}>Generate Code</button>
      </ViewHeader>
      {backendStatus === "unavailable" && codeState.status !== "success" && !visibleCode && (
        <p className="atlas-view-empty">Backend unavailable / code not generated.</p>
      )}
      {codeState.status === "empty" && !visibleCode && backendStatus !== "unavailable" && (
        <p className="atlas-view-empty">No generated code yet. Click Generate Code.</p>
      )}
      {codeState.status === "loading" && <p className="atlas-view-state">Generating code...</p>}
      {codeState.status === "error" && (
        <p className="atlas-view-error">Code generation failed: {codeState.message}</p>
      )}
      {(codeState.status === "success" && codeState.stale) ||
      (codeState.status !== "success" && "stale" in codeState && codeState.stale) ? (
        <p className="atlas-stale-warning">Generated code is stale because the model changed.</p>
      ) : null}
      {visibleCode && <pre className="atlas-code-block" aria-label="Generated CVXPY code">{visibleCode}</pre>}
    </section>
  );
}

export function AtlasSolutionView({
  solution,
  onSolve,
  onSelectVariable,
  onSelectConstraint
}: {
  solution: AtlasSolutionState;
  onSolve: () => void;
  onSelectVariable: (variableId: string) => void;
  onSelectConstraint: (constraintId: string) => void;
}) {
  const result =
    solution.status === "success"
      ? solution.result
      : solution.status === "loading" || solution.status === "error"
        ? solution.previous
        : null;

  return (
    <section className="atlas-view-panel atlas-solution-view" aria-label="Solution View">
      <ViewHeader
        eyebrow="Solution"
        title="Solver results"
        description="Solution state is separate from the editable model and becomes stale after edits."
      >
        <button type="button" onClick={onSolve}>Solve</button>
      </ViewHeader>
      {solution.status === "empty" && <p className="atlas-view-empty">No solve results yet.</p>}
      {solution.status === "loading" && <p className="atlas-view-state">Solving...</p>}
      {solution.status === "error" && <p className="atlas-view-error">{solution.message}</p>}
      {solution.status === "success" && solution.stale && (
        <p className="atlas-stale-warning">Solution is stale because the model changed after solving.</p>
      )}
      {solution.status !== "success" && "stale" in solution && solution.stale && (
        <p className="atlas-stale-warning">Previous solution is stale.</p>
      )}
      {result && <SolutionResult result={result} onSelectVariable={onSelectVariable} onSelectConstraint={onSelectConstraint} />}
    </section>
  );
}

export function AtlasDiagnosticsView({
  diagnostics,
  stale,
  onValidate,
  onSelectSource
}: {
  diagnostics: AtlasViewDiagnostic[];
  stale: boolean;
  onValidate: () => void;
  onSelectSource: (sourceId: string) => void;
}) {
  return (
    <section className="atlas-view-panel atlas-diagnostics-view" aria-label="Diagnostics View">
      <ViewHeader
        eyebrow="Diagnostics"
        title="Validation and runtime diagnostics"
        description="Aggregated frontend IR validation, backend diagnostics, solve diagnostics, and runtime diagnostics."
      >
        <button type="button" onClick={onValidate}>Validate</button>
      </ViewHeader>
      {stale && <p className="atlas-stale-warning">Diagnostics may be stale because the model changed.</p>}
      {diagnostics.length === 0 ? (
        <p className="atlas-view-empty">No diagnostics currently reported.</p>
      ) : (
        <ul className="atlas-view-diagnostics">
          {diagnostics.map((diagnostic) => (
            <li key={diagnostic.id} className={`atlas-diagnostic-${diagnostic.level}`}>
              <button
                type="button"
                disabled={!diagnostic.sourceId}
                onClick={() => diagnostic.sourceId && onSelectSource(diagnostic.sourceId)}
              >
                <strong>{diagnostic.level}</strong>
                <span>{diagnostic.message}</span>
                {diagnostic.sourceId && <em>{diagnostic.sourceId}</em>}
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

export function buildAtlasViewDiagnostics({
  ir,
  backendDiagnostics,
  runtimeDiagnostics,
  solution
}: {
  ir: AtlasIR;
  backendDiagnostics: string[];
  runtimeDiagnostics: AtlasRuntimeDiagnostic[];
  solution: AtlasSolutionState;
}): AtlasViewDiagnostic[] {
  const diagnostics: AtlasViewDiagnostic[] = [];
  validateAtlasIR(ir).forEach((message, index) => {
    diagnostics.push({ id: `frontend-${index}`, level: "error", message });
  });
  backendDiagnostics.forEach((message, index) => {
    diagnostics.push({ id: `backend-${index}`, level: message.toLowerCase().includes("error") ? "error" : "warning", message });
  });
  runtimeDiagnostics.forEach((diagnostic) => {
    diagnostics.push({
      id: `runtime-${diagnostic.cardId}-${diagnostic.diagnosticId}`,
      level: diagnostic.status === "error" ? "error" : diagnostic.status === "warning" || diagnostic.status === "stale" ? "warning" : "info",
      message: `${diagnostic.label}: ${diagnostic.value}`,
      sourceId: diagnostic.cardId
    });
  });
  const result = solution.status === "success" ? solution.result : solution.status === "loading" || solution.status === "error" ? solution.previous : null;
  result?.diagnostics.forEach((diagnostic, index) => {
    diagnostics.push({
      id: `solve-${index}`,
      level: diagnostic.level === "error" ? "error" : diagnostic.level === "warning" ? "warning" : "info",
      message: diagnostic.message,
      sourceId: diagnostic.sourceId
    });
  });
  return diagnostics;
}

function ViewHeader({
  eyebrow,
  title,
  description,
  children
}: {
  eyebrow: string;
  title: string;
  description: string;
  children: ReactNode;
}) {
  return (
    <header className="atlas-view-header">
      <div>
        <p className="atlas-eyebrow">{eyebrow}</p>
        <h2>{title}</h2>
        <span>{description}</span>
      </div>
      <div className="atlas-view-actions">{children}</div>
    </header>
  );
}

function SolutionResult({
  result,
  onSelectVariable,
  onSelectConstraint
}: {
  result: AtlasSolveResult;
  onSelectVariable: (variableId: string) => void;
  onSelectConstraint: (constraintId: string) => void;
}) {
  return (
    <div className="atlas-view-result-grid">
      <div className="atlas-solution-metric">
        <span>Solver status</span>
        <strong>{result.status}</strong>
      </div>
      <div className="atlas-solution-metric">
        <span>Objective value</span>
        <strong>{formatValue(result.objectiveValue)}</strong>
      </div>
      <section>
        <h3>Variable values</h3>
        {Object.keys(result.variableValues).length === 0 ? (
          <p className="atlas-muted">No variable values returned.</p>
        ) : (
          <ul className="atlas-result-list">
            {Object.entries(result.variableValues).map(([variableId, value]) => (
              <li key={variableId}>
                <button type="button" onClick={() => onSelectVariable(variableId)}>
                  <span>{variableId}</span>
                  <strong>{formatValue(value)}</strong>
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>
      <section>
        <h3>Constraint residuals</h3>
        {!result.constraints || Object.keys(result.constraints).length === 0 ? (
          <p className="atlas-muted">No constraint residuals returned.</p>
        ) : (
          <ul className="atlas-result-list">
            {Object.entries(result.constraints).map(([constraintId, constraint]) => (
              <li key={constraintId}>
                <button type="button" onClick={() => onSelectConstraint(constraintId)}>
                  <span>{constraintId}</span>
                  <strong>residual {formatValue(constraint.residual)}</strong>
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

function formatValue(value: unknown): string {
  if (typeof value === "number" && Number.isFinite(value)) return value.toLocaleString();
  if (Array.isArray(value)) return `[${value.map(formatValue).join(", ")}]`;
  return value === null || value === undefined ? "n/a" : String(value);
}
