import type { AtlasBackendDiagnostic } from "../api/backendClient";
import type {
  AtlasAtomObject,
  AtlasConnection,
  AtlasIR,
  AtlasModelObject
} from "../core/ir";

export type ColabNotebook = {
  cells: Array<{
    cell_type: "markdown" | "code";
    metadata: Record<string, unknown>;
    source: string[];
    outputs?: unknown[];
    execution_count?: number | null;
  }>;
  metadata: {
    kernelspec: {
      display_name: string;
      language: string;
      name: string;
    };
    language_info: {
      name: string;
      version: string;
    };
    colab?: Record<string, unknown>;
  };
  nbformat: 4;
  nbformat_minor: 5;
};

export type ColabGenerationResult = {
  code: string;
  notebook: ColabNotebook;
  filename: string;
  diagnostics: AtlasBackendDiagnostic[];
};

export function generateColabNotebook(ir: AtlasIR): ColabGenerationResult {
  const diagnostics: AtlasBackendDiagnostic[] = [];
  const code = generateCvxpyCodeForColab(ir, diagnostics);
  const title = ir.metadata?.title || "Atlas CVXPY Model";
  const exampleKind = inferExampleKind(ir, title);
  const expected = expectedResultText(title, exampleKind);
  const filename = notebookFilename(title, exampleKind);
  const notebook: ColabNotebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        name: "python",
        version: "3.x"
      },
      colab: {
        name: filename
      }
    },
    cells: [
      markdownCell([
        `# ${title}\n`,
        "\n",
        "Generated by Atlas Optimization Suite from Atlas IR.\n",
        "\n",
        "This notebook runs the generated CVXPY model in Colab or any Python environment with CVXPY installed.\n",
        expected ? `\n${expected}\n` : ""
      ]),
      codeCell(["%pip install -q cvxpy\n"]),
      codeCell(splitSource(code))
    ]
  };

  return {
    code,
    notebook,
    filename,
    diagnostics
  };
}

export function generateCvxpyCodeForColab(
  ir: AtlasIR,
  diagnostics: AtlasBackendDiagnostic[] = []
) {
  const names = cvxpyNameMap(ir);
  const usesNumpy = ir.modelObjects.constants.some((constant) => Array.isArray(constant.value));
  const lines = ["import cvxpy as cp"];
  if (usesNumpy) lines.push("import numpy as np");
  lines.push("");

  for (const variable of ir.modelObjects.variables) {
    lines.push(`${names[variable.id]} = cp.Variable(${shapeArgument(variable.shape)}name=${JSON.stringify(variable.name)})`);
  }
  if (ir.modelObjects.variables.length > 0) lines.push("");

  for (const constant of ir.modelObjects.constants) {
    if ("value" in constant) {
      lines.push(`${names[constant.id]} = ${constantCode(constant.value)}`);
    }
  }
  if (ir.modelObjects.constants.length > 0) lines.push("");

  const cache: Record<string, string> = {};
  for (const atom of ir.modelObjects.atoms) {
    lines.push(`${names[atom.id]} = ${expressionCode(ir, atom.id, names, cache, diagnostics)}`);
  }
  if (ir.modelObjects.atoms.length > 0) lines.push("");

  const objectiveId = firstProblemObjectiveId(ir) ?? ir.modelObjects.objectives[0]?.id;
  lines.push(
    objectiveId
      ? `objective = ${objectiveCode(ir, objectiveId, names, cache, diagnostics)}`
      : "objective = cp.Minimize(0)"
  );

  const constraintIds = firstProblemConstraintIds(ir);
  const activeConstraintIds = constraintIds.length > 0
    ? constraintIds
    : ir.modelObjects.constraints.map((constraint) => constraint.id);
  lines.push("constraints = [");
  for (const constraintId of activeConstraintIds) {
    lines.push(`    ${constraintCode(ir, constraintId, names, cache, diagnostics)},`);
  }
  lines.push("]");
  lines.push("problem = cp.Problem(objective, constraints)");
  lines.push("problem.solve()");
  lines.push('print("status", problem.status)');
  lines.push('print("objective", problem.value)');
  for (const variable of ir.modelObjects.variables) {
    lines.push(`print(${JSON.stringify(variable.name)}, ${names[variable.id]}.value)`);
  }

  return lines.join("\n");
}

export function notebookFilename(title: string, exampleKind: "tiny-lp" | "least-squares" | "ridge" | null = null) {
  if (exampleKind === "tiny-lp") return "atlas_tiny_lp.ipynb";
  if (exampleKind === "least-squares") return "atlas_least_squares.ipynb";
  if (exampleKind === "ridge") return "atlas_ridge_regression.ipynb";
  const normalized = title.toLowerCase();
  if (normalized.includes("tiny") && normalized.includes("lp")) return "atlas_tiny_lp.ipynb";
  if (normalized.includes("least") && normalized.includes("squares")) return "atlas_least_squares.ipynb";
  if (normalized.includes("ridge")) return "atlas_ridge_regression.ipynb";
  const safeTitle = normalized.replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "model";
  return `atlas_${safeTitle}.ipynb`;
}

function markdownCell(source: string[]): ColabNotebook["cells"][number] {
  return { cell_type: "markdown", metadata: {}, source };
}

function codeCell(source: string[]): ColabNotebook["cells"][number] {
  return { cell_type: "code", metadata: {}, source, outputs: [], execution_count: null };
}

function splitSource(source: string) {
  return source.split("\n").map((line) => `${line}\n`);
}

function expectedResultText(title: string, exampleKind: "tiny-lp" | "least-squares" | "ridge" | null) {
  if (exampleKind === "tiny-lp") return "Expected result: x = 2, y = 2, objective = 10.";
  if (exampleKind === "least-squares") return "Expected result: x approximately [1.1667, 0.5].";
  if (exampleKind === "ridge") return "Expected result: x approximately [0.8, 0.6].";
  const normalized = title.toLowerCase();
  if (normalized.includes("tiny") && normalized.includes("lp")) {
    return "Expected result: x = 2, y = 2, objective = 10.";
  }
  if (normalized.includes("least") && normalized.includes("squares")) {
    return "Expected result: x approximately [1.1667, 0.5].";
  }
  if (normalized.includes("ridge")) {
    return "Expected result: x approximately [0.8, 0.6].";
  }
  return "";
}

function inferExampleKind(ir: AtlasIR, title: string): "tiny-lp" | "least-squares" | "ridge" | null {
  const normalized = title.toLowerCase();
  if (normalized.includes("tiny") && normalized.includes("lp")) return "tiny-lp";
  if (normalized.includes("least") && normalized.includes("squares")) return "least-squares";
  if (normalized.includes("ridge")) return "ridge";

  const objectIds = new Set(allObjects(ir).map((item) => item.id));
  if (objectIds.has("atom-ridge-objective") || objectIds.has("const-lambda")) return "ridge";
  if (objectIds.has("atom-loss") && objectIds.has("atom-residual")) return "least-squares";
  if (objectIds.has("var-x") && objectIds.has("var-y") && objectIds.has("constraint-sum")) return "tiny-lp";
  return null;
}

function allObjects(ir: AtlasIR): AtlasModelObject[] {
  return [
    ...ir.modelObjects.variables,
    ...ir.modelObjects.parameters,
    ...ir.modelObjects.constants,
    ...ir.modelObjects.atoms,
    ...ir.modelObjects.expressions,
    ...ir.modelObjects.constraints,
    ...ir.modelObjects.objectives,
    ...ir.modelObjects.problems,
    ...ir.modelObjects.solvers,
    ...ir.modelObjects.results,
    ...ir.modelObjects.workspaceReferences
  ];
}

function cvxpyNameMap(ir: AtlasIR) {
  const names: Record<string, string> = {};
  const used = new Set<string>();
  for (const modelObject of allObjects(ir)) {
    const base = safePythonName(modelObject.name || modelObject.id);
    let candidate = base;
    let index = 2;
    while (used.has(candidate)) {
      candidate = `${base}_${index}`;
      index += 1;
    }
    names[modelObject.id] = candidate;
    used.add(candidate);
  }
  return names;
}

function expressionCode(
  ir: AtlasIR,
  objectId: string,
  names: Record<string, string>,
  cache: Record<string, string>,
  diagnostics: AtlasBackendDiagnostic[]
): string {
  if (cache[objectId]) return names[objectId] ?? cache[objectId];
  const modelObject = allObjects(ir).find((item) => item.id === objectId);
  if (!modelObject) {
    diagnostics.push({ level: "error", message: `Missing model object ${objectId}.`, sourceId: objectId });
    return `__missing_object__(${JSON.stringify(objectId)})`;
  }
  if (["variable", "parameter", "constant"].includes(modelObject.kind)) return names[objectId];
  if (modelObject.kind === "atom") {
    const connected = connectedInputs(ir, objectId);
    let sources = connected
      .sort((left, right) => slotSortKey(left.slot).localeCompare(slotSortKey(right.slot)))
      .map((input) => input.sourceId);
    if (sources.length === 0) {
      sources = fallbackAtomSources(modelObject);
    }
    const argCodes = sources.map((source) => expressionCode(ir, source, names, cache, diagnostics));
    const importPath = modelObject.importPath || modelObject.atomId || `cvxpy.${modelObject.atomName || modelObject.name}`;
    const code = atomCallCode(importPath, argCodes);
    cache[objectId] = code;
    return code;
  }
  return names[objectId] ?? modelObject.name;
}

function fallbackAtomSources(atom: AtlasAtomObject) {
  return atom.positionalInputs
    .map((input) => {
      if (typeof input === "object" && input !== null && "objectId" in input) {
        return String((input as { objectId?: unknown }).objectId ?? "");
      }
      return "";
    })
    .filter(Boolean);
}

function objectiveCode(
  ir: AtlasIR,
  objectiveId: string,
  names: Record<string, string>,
  cache: Record<string, string>,
  diagnostics: AtlasBackendDiagnostic[]
) {
  const objective = ir.modelObjects.objectives.find((item) => item.id === objectiveId);
  if (!objective) return "cp.Minimize(0)";
  const sources = connectedInputs(ir, objectiveId)
    .sort((left, right) => slotSortKey(left.slot).localeCompare(slotSortKey(right.slot)))
    .map((input) => input.sourceId);
  const expression = sources.length > 0
    ? sources.map((source) => expressionCode(ir, source, names, cache, diagnostics)).join(" + ")
    : "0";
  const direction = objective.objective?.direction === "maximize" ? "Maximize" : "Minimize";
  return `cp.${direction}(${expression})`;
}

function constraintCode(
  ir: AtlasIR,
  constraintId: string,
  names: Record<string, string>,
  cache: Record<string, string>,
  diagnostics: AtlasBackendDiagnostic[]
) {
  const constraint = ir.modelObjects.constraints.find((item) => item.id === constraintId);
  if (!constraint) return `# missing constraint ${constraintId}`;
  const inputs = Object.fromEntries(connectedInputs(ir, constraintId).map((input) => [input.slot, input.sourceId]));
  if (!inputs.lhs || !inputs.rhs) {
    diagnostics.push({ level: "warning", message: `Constraint ${constraintId} is incomplete.`, sourceId: constraintId });
    return `# incomplete constraint ${constraint.name}`;
  }
  const operator = constraint.constraint?.operator === "=" ? "==" : constraint.constraint?.operator ?? "<=";
  return `${expressionCode(ir, inputs.lhs, names, cache, diagnostics)} ${operator} ${expressionCode(ir, inputs.rhs, names, cache, diagnostics)}`;
}

function firstProblemObjectiveId(ir: AtlasIR) {
  const problem = ir.modelObjects.problems[0];
  if (!problem) return null;
  return connectedInputs(ir, problem.id).find((input) => input.slot === "objective")?.sourceId ?? null;
}

function firstProblemConstraintIds(ir: AtlasIR) {
  const problem = ir.modelObjects.problems[0];
  if (!problem) return [];
  return connectedInputs(ir, problem.id)
    .filter((input) => input.slot === "constraints")
    .map((input) => input.sourceId);
}

function connectedInputs(ir: AtlasIR, targetObjectId: string) {
  const nodeToObject = Object.fromEntries(ir.workspaceNodes.map((node) => [node.id, node.modelObjectId]));
  const inputs: Array<{ slot: string; sourceId: string }> = [];
  for (const connection of ir.connections as AtlasConnection[]) {
    const targetId = connection.target.objectId ?? (
      connection.target.nodeId ? nodeToObject[connection.target.nodeId] : undefined
    );
    if (targetId !== targetObjectId) continue;
    const sourceId = connection.source.objectId ?? (
      connection.source.nodeId ? nodeToObject[connection.source.nodeId] : undefined
    );
    if (sourceId) inputs.push({ slot: connection.target.slot ?? "arg0", sourceId });
  }
  return inputs;
}

function atomCallCode(importPath: string, argCodes: string[]) {
  if (importPath === "atlas.expression.add") return argCodes.length > 0 ? `(${argCodes.join(" + ")})` : "0";
  if (importPath === "atlas.expression.subtract") return argCodes.length >= 2 ? `(${argCodes[0]} - ${argCodes[1]})` : "# incomplete subtract";
  if (importPath === "atlas.expression.multiply") return argCodes.length >= 2 ? `(${argCodes[0]} * ${argCodes[1]})` : "# incomplete multiply";
  if (importPath === "atlas.expression.matmul") return argCodes.length >= 2 ? `(${argCodes[0]} @ ${argCodes[1]})` : "# incomplete matmul";
  const atomName = importPath.replace(/^cvxpy\./, "").split(".").at(-1) || importPath;
  return `cp.${atomName}(${argCodes.join(", ")})`;
}

function constantCode(value: unknown): string {
  if (Array.isArray(value)) return `np.array(${JSON.stringify(value)})`;
  return JSON.stringify(value);
}

function shapeArgument(shape: unknown) {
  const normalized = cvxpyShape(shape);
  return normalized.length > 0 ? `${JSON.stringify(normalized)}, ` : "";
}

function cvxpyShape(shape: unknown): number[] {
  if (typeof shape === "number" && shape > 0) return [shape];
  if (Array.isArray(shape) && shape.every((item) => Number.isInteger(item) && Number(item) > 0)) {
    return shape.map(Number);
  }
  if (typeof shape === "object" && shape !== null) {
    const raw = (shape as { dimensions?: unknown; shape?: unknown }).dimensions ?? (shape as { shape?: unknown }).shape;
    if (Array.isArray(raw) && raw.every((item) => Number.isInteger(item) && Number(item) > 0)) {
      return raw.map(Number);
    }
  }
  return [];
}

function safePythonName(value: string) {
  const candidate = value.trim().replace(/\W+/g, "_").replace(/^_+|_+$/g, "") || "obj";
  const safe = /^\d/.test(candidate) ? `obj_${candidate}` : candidate;
  return PYTHON_KEYWORDS.has(safe) ? `${safe}_` : safe;
}

function slotSortKey(slot: string) {
  const match = /^(arg|term)(\d+)$/.exec(slot);
  return match ? `${String(Number(match[2])).padStart(4, "0")}:${slot}` : `9999:${slot}`;
}

const PYTHON_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
  "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
  "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
  "with", "yield"
]);
